"""Canonical market-store physical contracts; no network or live dependencies."""

from grid_market_store.physical import (
    BUCKET_ALGORITHM_ID,
    BUCKET_COUNT,
    CANONICAL_LAYOUT_ID,
    COMPRESSION,
    COMPRESSION_LEVEL,
    EXACT_PHYSICAL_CONTRACT,
    NUMERIC_REPRESENTATION,
    PRICE_SCALE,
    TARGET_FILE_SIZE_BYTES,
    TURNOVER_SCALE,
    VOLUME_SCALE,
    CanonicalCandleBatch,
    PhysicalContractError,
    build_canonical_candle_batch,
    canonical_candle_schema,
    canonical_partition_path,
    stable_bucket,
    verify_canonical_candle_schema,
)
from grid_market_store.publication import (
    AUDIT_CONTRACT,
    MAX_MEMORY_PERCENT,
    MIN_OPERATING_RESERVE_BYTES,
    PUBLICATION_CONTRACT,
    CandleDatasetSpec,
    CapacityBudget,
    HostSnapshot,
    PublicationError,
    PublicationPlan,
    PublishedDataset,
    load_committed_candle_table,
    preflight_candle_dataset,
    publish_candle_dataset,
    verify_committed_candle_dataset,
)

__all__ = [
    "AUDIT_CONTRACT",
    "BUCKET_ALGORITHM_ID",
    "BUCKET_COUNT",
    "CANONICAL_LAYOUT_ID",
    "COMPRESSION",
    "COMPRESSION_LEVEL",
    "EXACT_PHYSICAL_CONTRACT",
    "MAX_MEMORY_PERCENT",
    "MIN_OPERATING_RESERVE_BYTES",
    "NUMERIC_REPRESENTATION",
    "PRICE_SCALE",
    "PUBLICATION_CONTRACT",
    "TARGET_FILE_SIZE_BYTES",
    "TURNOVER_SCALE",
    "VOLUME_SCALE",
    "CandleDatasetSpec",
    "CanonicalCandleBatch",
    "CapacityBudget",
    "HostSnapshot",
    "PhysicalContractError",
    "PublicationError",
    "PublicationPlan",
    "PublishedDataset",
    "build_canonical_candle_batch",
    "canonical_candle_schema",
    "canonical_partition_path",
    "load_committed_candle_table",
    "preflight_candle_dataset",
    "publish_candle_dataset",
    "stable_bucket",
    "verify_canonical_candle_schema",
    "verify_committed_candle_dataset",
]

__version__ = "0.2.0"
